# Generated by Django 6.0.5 on 2026-05-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('has_part_1', models.BooleanField(default=False, verbose_name='Part I')),
                ('has_part_2', models.BooleanField(default=False, verbose_name='Part II')),
                ('has_part_3', models.BooleanField(default=False, verbose_name='Part III')),
                ('has_part_4', models.BooleanField(default=False, verbose_name='Part IV')),
                ('format', models.CharField(choices=[('full_time', 'Vollzeit'), ('part_time', 'Teilzeit'), ('part_or_full', 'Teil- oder Vollzeit')], max_length=20)),
                ('teaching_mode', models.CharField(choices=[('presence', 'Präsenz'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='presence', max_length=20, verbose_name='Unterrichtsform')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (hours)')),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Course fee in EUR, excluding exam fees.', max_digits=8, null=True)),
                ('exam_fee_scraped', models.DecimalField(blank=True, decimal_places=2, help_text='Exam fee as stated on this specific course page. May cover one or multiple parts. The ExamFee model holds the per-part breakdown for the total-cost calculator.', max_digits=8, null=True, verbose_name='Prüfungsgebühr (scraped)')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('availability', models.CharField(choices=[('available', 'Freie Plätze'), ('few_spots', 'Wenige Plätze'), ('full', 'Ausgebucht'), ('unknown', 'Unbekannt')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offers', to='chambers.chamber')),
                ('trade', models.ForeignKey(blank=True, help_text='Leave blank for generic Parts III+IV courses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offers', to='chambers.trade')),
            ],
            options={
                'verbose_name': 'Course Offer',
                'verbose_name_plural': 'Course Offers',
                'ordering': ['chamber__name', 'trade__name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(choices=[(1, 'Part I   – Practical/technical'), (2, 'Part II  – Theory/technical'), (3, 'Part III – Business administration'), (4, 'Part IV  – Vocational training')])),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scraper_may_overwrite', models.BooleanField(default=True)),
                ('manually_verified', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('scraped', 'Scraped automatically'), ('pdf_manual', 'Taken from PDF (manually entered)'), ('admin_manual', 'Entered via admin interface')], default='scraped', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_fees', to='chambers.chamber')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_fees', to='chambers.trade')),
            ],
            options={
                'verbose_name': 'Exam Fee',
                'verbose_name_plural': 'Exam Fees',
                'ordering': ['chamber__name', 'trade__name', 'part'],
                'unique_together': {('chamber', 'trade', 'part')},
            },
        ),
    ]
