# Generated by Django 6.0.5 on 2026-05-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some errors)'), ('failed', 'Failed'), ('skipped', 'Skipped (site unreachable)')], default='success', max_length=20)),
                ('offers_created', models.PositiveIntegerField(default=0, help_text='Number of new TradeOffer records created')),
                ('offers_updated', models.PositiveIntegerField(default=0, help_text='Number of existing TradeOffer records updated')),
                ('bundles_created', models.PositiveIntegerField(default=0, help_text='Number of new CourseBundle records created')),
                ('bundles_updated', models.PositiveIntegerField(default=0, help_text='Number of existing CourseBundle records updated')),
                ('exam_fees_updated', models.PositiveIntegerField(default=0, help_text='Number of ExamFee records updated (scraper_may_overwrite=True only)')),
                ('error_log', models.TextField(blank=True, help_text='Full error output or traceback if the run failed or was partial')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chamber', models.ForeignKey(blank=True, help_text='The chamber this run targeted (null = full pipeline run)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_runs', to='chambers.chamber')),
            ],
            options={
                'verbose_name': 'Scraper Run',
                'verbose_name_plural': 'Scraper Runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
