#!/usr/bin/env python
"""
scripts/import_manual_fees_from_live.py

Recover the hand-curated exam fees from the OLD live site instead of exporting
from the database. The legacy AFBG page embeds the full per-part exam-fee table
as ``var EXAM_FEES = {...}`` (DB ids), plus ``var CHAMBERS`` / ``var TRADES``
which carry the id→slug mapping.

Only the chambers whose exam fees are manually curated (HWK Koblenz, HWK
Rheinhessen) are written to data/manual/exam_fees_manual.json — the scraped
chambers (Trier, Pfalz, Saarland) are regenerated by the scrapers themselves.

Usage:
    python scripts/import_manual_fees_from_live.py
    python scripts/import_manual_fees_from_live.py --url https://meisterkompass.onrender.com/afbg/
"""

import argparse
import json
import re
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "data" / "manual" / "exam_fees_manual.json"
DEFAULT_URL = "https://meisterkompass.onrender.com/afbg/"

# Chambers whose exam fees exist only as manual admin entries.
MANUAL_CHAMBERS = {"hwk-koblenz", "hwk-rheinhessen"}


def _extract(html: str, var: str):
    m = re.search(rf"var {var}\s*=\s*(\{{.*?\}}|\[.*?\]);", html, re.DOTALL)
    if not m:
        raise SystemExit(f"Could not find `var {var}` in the page.")
    return json.loads(m.group(1))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=DEFAULT_URL)
    args = ap.parse_args()

    req = urllib.request.Request(args.url, headers={"User-Agent": "Mozilla/5.0"})
    html = urllib.request.urlopen(req, timeout=120).read().decode("utf-8")

    exam_fees = _extract(html, "EXAM_FEES")
    chamber_by_id = {str(c["id"]): c["slug"] for c in _extract(html, "CHAMBERS")}
    trade_by_id = {str(t["id"]): t["slug"] for t in _extract(html, "TRADES")}

    rows = []
    for cid, by_trade in exam_fees.items():
        chamber_slug = chamber_by_id.get(cid)
        if chamber_slug not in MANUAL_CHAMBERS:
            continue
        for tid, by_part in by_trade.items():
            trade_slug = None if tid == "null" else trade_by_id.get(tid, tid)
            for part, v in by_part.items():
                rows.append({
                    "chamber_slug": chamber_slug,
                    "trade_slug":   trade_slug,
                    "part":         int(part),
                    "fee":          v["fee"],
                    "fee_max":      v.get("fee_max"),
                    "qualifier":    v.get("qualifier") or "",
                })

    rows.sort(key=lambda r: (r["chamber_slug"], r["trade_slug"] or "", r["part"]))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    chambers = sorted({r["chamber_slug"] for r in rows})
    print(f"Wrote {len(rows)} manual exam-fee row(s) for {chambers} → {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
